//--------------------------------------------------------------------------------------
// Copyright (c) 2025 BattleAxeVR. All rights reserved.
//--------------------------------------------------------------------------------------

#ifndef BVR_DEFINES_H__
#define BVR_DEFINES_H__

namespace BVR
{
	const int LEFT = 0;
	const int RIGHT = 1;
	const int NUM_EYES = 2;
}

#define ENABLE_DUMMY_ET_GAZES 1
#define EYE_TRACKING_POLLING_RATE_MS 4

#define ENABLE_PSVR2_EYE_TRACKING 1
#define ENABLE_PSVR2_EYE_TRACKING_SOCKETS (ENABLE_PSVR2_EYE_TRACKING && 0)
#define ENABLE_PSVR2_EYE_TRACKING_NAMED_PIPES (!ENABLE_PSVR2_EYE_TRACKING_SOCKETS && 1)

#define ENABLE_PSVR2_EYE_TRACKING_AUTOMATICALLY (ENABLE_PSVR2_EYE_TRACKING && 1)
#define ENABLE_GAZE_CALIBRATION (ENABLE_PSVR2_EYE_TRACKING && 0)
#define ENABLE_PSVR2_EYE_TRACKING_COMBINED_GAZE (ENABLE_PSVR2_EYE_TRACKING && 1)
#define ENABLE_PSVR2_EYE_TRACKING_PER_EYE_GAZES (ENABLE_PSVR2_EYE_TRACKING && 0)
#define AUTO_CALIBRATE (ENABLE_PSVR2_EYE_TRACKING && 0)
#define AUTO_INCREMENT_ON_CALIBRATION_DONE 0

#define INVALID_INDEX -1

#ifndef FORCE_EXT
#define FORCE_EXT 0
#endif

#ifndef FORCE_SOCIAL
#define FORCE_SOCIAL 0
#endif

#define ENABLE_DUMMY_EXT_COMBINED_GAZE 0
#define ENABLE_PSVR2_EXT_COMBINED_GAZE FORCE_EXT

#define ENABLE_DUMMY_SOCIAL_GAZES 0
#define ENABLE_PSVR2_SOCIAL_GAZES FORCE_SOCIAL

#define ENABLE_SOCIAL_GAZES (ENABLE_DUMMY_SOCIAL_GAZES || ENABLE_PSVR2_SOCIAL_GAZES)
#define ENABLE_EXT_GAZE_INTERACTION (ENABLE_DUMMY_EXT_COMBINED_GAZE || ENABLE_PSVR2_EXT_COMBINED_GAZE)

#define ENABLE_BOTH_PSVR2_LAYERS (ENABLE_PSVR2_EXT_COMBINED_GAZE && ENABLE_PSVR2_SOCIAL_GAZES)

#define SUPPORT_QUEST_PRO 0
#define SUPPORT_STEAMLINK 0
#define SUPPORT_VIRTUAL_DESKTOP 0
#define SUPPORT_WMR 0
#define SUPPORT_SIMULATED_EYE_TRACKING 0

#endif // BVR_DEFINES_H__

